### PR TITLE
Process multiple files and other tweaks

### PR DESCRIPTION
**Pull request by danishalim**
Enabled processing multiple files, made code more modular, used try..catch blocks and used best practices code e.g. removed "process.exit" and replaced with "throw."

### CODE REVIEW

**Review by hyunjiLeeTech — COMMENTED** [review]
Thank you for your pull request. I've found some issues on your change.
When I process my tool using any argument, it doesn't work.
For example, if I enter 'url-fi -s test.html', it gives me an error.
My previous code allows me to enter multiple arguments at the same time so please check this. (e.g. url-fi -shv test.html) 
Thanks.

**Comment by danishalim** [comment]
Hi, I have fixed the options parsing issue. All options work now including the "s" option.

**Review by hyunjiLeeTech — COMMENTED** [review]
Can you please check it again? When I enter 'url-fi -sh test.html', it only displays the help messages without working -s option. Thank you.

**Comment by danishalim** [comment]
That is odd. It works fine on my end. https://imgur.com/a/Z2ebRtf. Did you test this PR?

**Review by hyunjiLeeTech — COMMENTED** [review]
Hi, I've checked your code and see it works at some point. However, it has one point missed from my expectation. 
In my tool, I would like to put argument located in any places (e.g., 'url-fi -hvs test.html' and 'url-fi test.html -hvs' display the same result. However, when I look at your code, it seems that if the first one in a loop does not include '-', it goes to check url function. Let me know if I did not figure out your code. Thanks.

**Pull request closed without merging**
