### PR TITLE
Add new feather for arg --ignore

### PR DESCRIPTION
**Pull request by tianlangwu**
Added the feather discussed in  [issue#12](https://github.com/hyunjiLeeTech/URL-FI/issues/12). 
The test result shows below:
Ignore.txt contains all the URLs that test.txt have except the "s9y.org". The result will print only "s9y.org"
IGNORE1
Updated the README file for new arguments.
Please let me know if I did anything incorrectly, thanks!

### CODE REVIEW

**Review by hyunjiLeeTech — COMMENTED** [review]
image
I've tested ignore.txt file editing to include 'http://s9y.org', but it doesn't work (I added a picture for it). Can you double-check whether it is working? If I am doing incorrectly, let me know.

**Comment by tianlangwu** [comment]
It because the function is not synchronous, sometimes it might run the second readFile first. Because your readFile function is not synchronous, so I didn't make a synchronous read too. 
let me try to make the synchronous function for both readFile.

**Comment by tianlangwu** [comment]
can you try to add "async" keyword here, it works for me 
async

**Comment by tianlangwu** [comment]
Can you try it multiple times?  Does it work most time?  I believe it is sync problem but not sure.

I noticed that you are using global command url-fi, did you install the newest version? can u try "node index --ignored?

**Comment by hyunjiLeeTech** [comment]
I've installed a new version. When I tried it multiple times (with async), sometimes it works but sometimes not. The percentage is around 50%. But it is the same when I did not add async.

**Comment by tianlangwu** [comment]
yes, we can't just add async. I believe there is more stuff to do to make the request async. I will give it a try later.

**Comment by hyunjiLeeTech** [comment]
Let me know when you've done. Thanks.

**Comment by tianlangwu** [comment]
Can you try now?

**Comment by hyunjiLeeTech** [comment]
It almost works! However, when I add '#http://s9y.org' on the ignore.txt file, the program ignores this url too. Following our instruction, the line starts with # should be treated as comment. Can you take a look at this?

**Comment by tianlangwu** [comment]
oh, I forget about # stuff, I will do it tomorrow. Thanks for reminding me that.

**Comment by tianlangwu** [comment]
I fixed it, can you please check :D

**Comment by hyunjiLeeTech** [comment]
image
It seems only comment works. Can you double check it and tell me if I did incorrectly?

**Comment by tianlangwu** [comment]
It works perfectly when I tested
ig01
ig02

**Comment by tianlangwu** [comment]
are you on slack? we can discuss it there. You can send me your test file?

**Comment by hyunjiLeeTech** [comment]
Sure. I will send you my test file

**Pull request merged**
