### PR TITLE
Added passing directory path options!!

### LINKED ISSUE #5: [Suggestion] allow passing directory paths vs. file paths, and recursively process all children under that directory
Your program doesn't seem to support accept a directory paths options. 
For example, [toolName] --recursive <dirName> should process all the files in the directory. 
I would like to add this feature on your project!!

### PR DESCRIPTION
**Pull request by klee214**
Fixes #5 As I mentioned in the issues section, I have added this new optional feature to your code! I tried to keep following your code alignment and styles, but if something doesn't look good, please let me know!

I have created `function CliHelpMsg()` for displaying help messages. Also, `function findFilesInDir(path)`  is finding files in the passed path. I added -r optional argument in your program
```
        if (arg.includes("r")) {
            findFilesInDir(process.argv[3])
        }
```
And I have added some example instruction in CLI 
```   
       console.log("Usage : url-fi -s [FILENAME]")
       console.log("Usage : url-fi -r [DIRECTORY_PATH]")
```

### CODE REVIEW

**Review by hyunjiLeeTech — COMMENTED** [review]
Thank you for your idea! I've reviewed your code and find some issues. Can you please have a look at them?

1. Please check the argument section of the README file and make a newline for each part. 
2. In my previous code, I allow users to enter multiple arguments at the same time (e.g., url-fi -hvs test.html). But when I use your code, it doesn't allow to do this (e.g., url-fi -hs test.html). Can you please check this?
3. When I use this tool without any arguments, it does not work
4. When I use -r argument with file (not directory), it gives an error (ENOTDIR: not a directory, scandir 'test.html). Can you make it print message rather than error?

Thanks

**Comment by klee214** [comment]
Thank you for your feedback!
I fixed all the issues you told me!
Let me know if you find any bug or problem on the program!!

**Comment by klee214** [comment]
I found some bug on my commit, so hold on please!! I will fix it and then commit again sooner or later

**Comment by hyunjiLeeTech** [comment]
Ok. Let me know when you've done

**Comment by klee214** [comment]
Sorry i have been too busy recently, so i didn't focus on this commit. I will continue this work tomorrow and will finish hopefully before Saturday night

**Comment by klee214** [comment]
I fix the minor bug which is your `const regex = /(http(s)?:\/\/.)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/g`
"?" symbol following `https` mean zero or one `https`.

**Comment by hyunjiLeeTech** [comment]
It works! Thanks.

**Pull request merged**
